### ISSUE TITLE
Show hours for different locations

### ISSUE THREAD

**Issue by thebrianzeng** [ADI-Labs/density#67]
it would be cool to know if a place is closed or not. or when the place opens/closes.

**Comment by jzf2101** [comment]
That would definitely cover 80% of it.  Sometimes the schedules are weird though.  Let's see if we can get something from the libraries to avoid weird changes in schedule from holidays etc.

**Comment by chmullig** [comment]
I wonder if at least the Libraries would be willing to expose an API? They just added this last year: http://hours.library.columbia.edu/study-spaces-open-now.php

**Comment by natebrennand** [comment]
We're in talks w/ CUIT for a variety of data sources, for now we'll probably just manually update it for now. Or we could hardcode the availability since it's [already set for the rest of the school year](http://hours.library.columbia.edu/summary.php) but that would be tedious.

**Comment by swbae31** [comment]
![2015-03-27 5 22 13 pm](https://cloud.githubusercontent.com/assets/6799284/6877292/0e6391f0-d4a6-11e4-90e8-59d037935739.png)

Scraping from http://hours.library.columbia.edu/study-spaces-open-now.php but don't have closing time for Lerner, jjs, John Jay Dining Hall, Roone Arledge Auditorium, and Butler Library Stacks

**Comment by jzf2101** [comment]
:+1:

**Comment by swbae31** [comment]
So the hours are now scraped from three places
- gen libs : http://hours.library.columbia.edu/study-spaces-open-now.php
- dining halls :http://dining.columbia.edu/?quicktabs_homepage_menus_quicktabs={num}#quicktabs-homepage_menus_quicktabs
- butler stacks : http://hours.library.columbia.edu/?library=butler

and Lerner just uses static weekly hours

![image](https://cloud.githubusercontent.com/assets/6799284/7327185/3506d5e8-ea99-11e4-9cf2-ed8526c2b433.png)

but one prob is that the hours have two formats. 
1) until 9:00 pm
2) 9:00 am ~ 9:00 pm

should I unify the format? which would take some amount of datetime coding.
converting everything to the 1) format

**Comment by evantarrh** [comment]
@swbae31 I would say not to worry about changing it. Everything is clear and makes sense as it is. I vote for :ship: it

**Comment by jzf2101** [comment]
@swbae31 :ship: for now and we'll fix formatting later.

**Comment by thebrianzeng** [comment]
yeah, i think the format looks good right now.

**Comment by swbae31** [comment]
k i'll :ship:  after I add some error handling code with scraping

**Comment by evantarrh** [comment]
what is the current status on this? would be super cool if we could get a PR up by the end of today

**Comment by jzf2101** [comment]
@samw7823 we're closed on this right?

**Comment by alanhdu** [comment]
@swbae31 Did you get around to shipping this?

**Comment by evantarrh** [comment]
:’)
